global:
  hostname: studio-test.cfabric.org
  environmentName: test
  environmentType: test

backend:
  image:
    tag: "sha-REPLACE_ME"
  replicas: 1
  database:
    existingSecret: studio-postgres-app
    keys:
      host: host
      port: port
      user: username
      password: password
      dbname: dbname
  autoscaling:
    enabled: false
  sessions:
    enabled: false
  configOverride:
    existingConfigMap: ""
  idpAdmin:
    baseUrl: "https://studio-test.cfabric.org/auth"
  fileStorage:
    enabled: true
    s3:
      bucket: test-webstudio

frontend:
  image:
    tag: "sha-REPLACE_ME"
  replicas: 1
  autoscaling:
    enabled: false

frontendPrototype:
  enabled: true
  hostname: studio-test-poc.cfabric.org
  image:
    tag: "sha-REPLACE_ME"

keycloak:
  enabled: true
  replicas: 2
  hostname: studio-test.cfabric.org
  relativePath: /auth
  image:
    tag: "sha-REPLACE_ME"

ingress:
  enabled: true
  className: traefik
