{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "studio-web.serviceAccountName" . }}
  labels: {{- include "studio-web.labels" . | nindent 4 }}
{{- end }}
