/**
 * Header Component
 *
 * Titles the content area with the currently-mounted screen. Identity and
 * sign-out live at the foot of the menu (see Menu.tsx), so the header belongs
 * entirely to the screen.
 * Generated by `frontx scaffold layout`.
 */

import React from 'react';
import {
  useMountedExtensions,
  FRONTX_SCREEN_DOMAIN,
  type ScreenExtension,
} from '@gears-frontx/react';

export interface HeaderProps {
  children?: React.ReactNode;
}

export const Header: React.FC<HeaderProps> = ({ children }) => {
  const mountedScreens = useMountedExtensions(FRONTX_SCREEN_DOMAIN) as ScreenExtension[];
  const title = mountedScreens[0]?.presentation?.label;

  return (
    <header className="h-16 flex items-center gap-4 px-4 border-b border-border bg-background">
      {title && <h1 className="text-heading-1 font-semibold text-foreground">{title}</h1>}
      {children}
    </header>
  );
};

Header.displayName = 'Header';
